name: android-ijkplayer-aar

on:
  # push:
  #   branches: [master]
  # pull_request:
  #   branches: [master]
  workflow_dispatch:
    inputs:
      beta:
        type: boolean
        description: publish beta edition
        default: true
        required: false
jobs:
  build:
    name: build-android-ijk-aar
    runs-on: macos-14

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          submodules: recursive
          
    #递归初始化和更新子模块
    #- name: Initialize and update submodules
    #  run: |
    #    git submodule update --init --recursive
    #    git submodule update --remote  # 拉取子模块最新提交[2,6](@ref)

    - name: Prepare Beta Version
      if: ${{ inputs.beta == true }}
      run: |
        grep -m 1 VERSION_NAME= version.sh | awk -F = '{printf "VERSION=%s",$2}' | xargs > constants.env
        echo "RELEAE_DATE=$(TZ=UTC-8 date +'%y%m%d%H%M%S')" >> constants.env
        echo "TAG=k"$(grep "VERSION" constants.env | cut -d'=' -f2)"-beta-"$(grep "RELEAE_DATE" constants.env | cut -d'=' -f2) >> constants.env
        cat constants.env
    - name: Prepare Normal Version
      if: ${{ inputs.beta == false }}
      run: |
        grep -m 1 VERSION_NAME= version.sh | awk -F = '{printf "TAG=k%s",$2}' | xargs > constants.env
        cat constants.env
    - name: Export Env
      uses: cardinalby/export-env-action@v2
      with:
        envFile: 'constants.env'
    - name: Download Pre Compiled Dependencies
      run: cd android && ./install-ffmpeg.sh
    - name: Build android arr
      run: cd android && ./build-aar.sh
    - name: Upload Release Asset
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        branch=$(git branch --show-current)
        gh release create ${{ env.TAG }} --target $branch -t "👏👏 ijkplayer-cmake-aar ${{ env.TAG }}" android/ijkplayer/ijkplayer-cmake/build/outputs/aar/*.*
